### ISSUE TITLE
instant results not working anymore

### ISSUE THREAD

**Issue by frufru666** [Sheraff/urbandictionary-alfred-workflow#1]
results on written query don't appear in Alfred anymore before pressing Enter. 
![screen shot 2018-08-15 at 10 57 54](https://user-images.githubusercontent.com/33035240/44140343-13f1efb0-a07a-11e8-984a-6c8e8bf7a20d.png)

**Comment by chrishough** [comment]
I am having the same problem, has anyone dived in to this?

**Comment by zvaehn** [comment]
Thats because the API's response changed. There is no more key "exact" given in the json.
You can fix this by removing those lines in the workflow's script filter.

**Comment by chrishough** [comment]
@zvaehn do you have a PR open for this?

**Comment by zvaehn** [comment]
unfortunately not, because i just implemented this little fix locally and it would take some functionality from the workflow. I did not take a deeper look into the api to check if there is another workaround for this.

**Comment by chrishough** [comment]
cool, so this is still a pending bug @zvaehn

**Comment by chrishough** [comment]
Thank you @Sheraff

**Comment by chrishough** [comment]
@Sheraff I tried this again on the latest version downloaded and it is still not working?  Are you able to duplicate this?

**Comment by Sheraff** [comment]
> @Sheraff I tried this again on the latest version downloaded and it is still not working? Are you able to duplicate this?

Nope, this works for me...

**Comment by chrishough** [comment]
Ok, I tried this again @Sheraff and it is still borked.  I never see the fetched results, only the link to hit urban dictionary directly. Thoughts on a fix or what I am doing wrong here?
